config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  post '/create_contact', to: 'pages#create_contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :phone, numericality: { only_integer: true },
  length: { minimum: 8, maximum: 15 }
  validates :body, presence: true, length: { minimum: 10, maximum: 1000 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @contact = Contact.new
  end

  def create_contact
    @contact = Contact.new(contact_params)
    if @contact.save
      flash[:success] = "Votre message a été envoyé avec succès."
      redirect_to root_path
    else
      flash.now[:error] = "Une erreur est survenue. Veuillez vérifier vos informations."
      render :home
    end
  end


  private

  def contact_params
    params.require(:contact).permit(:name, :email, :phone, :company, :city, :subject, :body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Inaamane</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bruno+Ace&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bruno+Ace&family=Maven+Pro:wght@500&display=swap" rel="stylesheet">

  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<%= render "shared/banner" %>



<%# Mes services %>
<div class="title-services">
  <h4>Ce que je propose</h4>
  <h2>SERVICES</h2>
</div>

<div class="line-container">
  <div class="line"></div>
  <div class="square-container">

    <div class="square">
      <h3>Gestion de projet</h3>
      <i class="fa-solid fa-rocket"></i>
      <div class="magic-hat-content">
        <p>Design de site internet, Application web & mobile, Mise en page de contenu</p>
      </div>
    </div>

    <div class="square">
      <h3>Web design</h3>
      <i class="fa-sharp fa-solid fa-wand-magic-sparkles"></i>
      <div class="magic-hat-content">
        <p>Votre identité de marque (logo, design de tous supports web) est créée sur mesure pour répondre aux besoins de votre cible.</p>
      </div>
    </div>

    <div class="square">
      <h3>Création de sites internet</h3>
      <i class="fa-solid fa-code"></i>
      <div class="magic-hat-content">
        <p>La création de site web est indispensable pour améliorer la visibilité de ses activités. Le développement de votre site web est réalisé avec soin et répond aux standards web du W3C.</p>
      </div>
    </div>

    <div class="square">
      <h3>Optimisation SE0</h3>
      <i class="fa-solid fa-signal"></i>
      <div class="magic-hat-content">
        <p>Votre site internet est développé avec pour objectif d’apparaître dans les premières pages sur les moteurs de recherche.</p>
      </div>
    </div>

    <div class="square">
      <h3>Hébergement et maintenance</h3>
      <i class="fa-solid fa-server"></i>
      <div class="magic-hat-content">
        <p>Services d'hébergement web fiables et sécurisés pour garantir la disponibilité et la performance optimale de votre site web. </p>
      </div>
    </div>

  </div>
</div>



<div class="title-competences">
  <h4>Ce que je sais faire</h4>
  <h2>COMPETENCES</h2>
</div>


<%#
<section class="skills">
  <h2>Mes compétences en informatique</h2>
  <ul>
    <li>
      <h3>Programmation</h3>
      <p>Maîtrise des langages suivants : HTML, CSS, JavaScript, Ruby, Python, Java.</p>
      <div class="skill-level" data-level="90"></div>
    </li>
    <li>
      <h3>Design d'interfaces</h3>
      <p>Expérience en design d'interfaces utilisateur pour des applications web et mobiles.</p>
      <div class="skill-level" data-level="80"></div>
    </li>
    <li>
      <h3>Bases de données</h3>
      <p>Connaissances en SQL et en gestion de bases de données relationnelles.</p>
      <div class="skill-level" data-level="70"></div>
    </li>
  </ul>
</section> %>

<section class="skills" data-controller="skills">
  <div class="skill" data-skills-target="progress">
    <h3>Compétence 1</h3>
    <div class="progress">
      <div class="progress-bar" data-level="80"></div>
    </div>
  </div>
  <div class="skill" data-skills-target="progress">
    <h3>Compétence 2</h3>
    <div class="progress">
      <div class="progress-bar" data-level="60"></div>
    </div>
  </div>
  <div class="skill" data-skills-target="progress">
    <h3>Compétence 3</h3>
    <div class="progress">
      <div class="progress-bar" data-level="40"></div>
    </div>
  </div>
</section>











<%# contact %>
<div class="wrapper-contact">
  <div class="title-contact">
    <h4>Envie d'échanger?</h4>
    <h2>CONTACT</h2>
  </div>
  <div class="container-contact">
    <div class="contact-infos">
      <div class="image-container">
        <img src="https://images.unsplash.com/photo-1581291519195-ef11498d1cf2?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NjN8fHNlcnJhZ2UlMjBkZSUyMG1haW5zfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60" alt="Image" />
      </div>
      <div class="contact-details">
        <h3>Ines Naamane</h3>

        <div class="infos">
          <h4>Téléphone</h4>
          <p> 07 62 23 12 45</p>
        </div>

        <div class="infos">
          <h4>Email</h4>
          <p>i.naamane@gmail.com</p>
        </div>

        <div class="infos">
          <h4>Adresse</h4>
          <p>71 Rue Pierre Joseph Proud'hon, La Seyne Sur Mer, France</p>
        </div>

      </div>
    </div>
    <div class="contact-form">
      <%= simple_form_for :contact, url: create_contact_path do |f| %>
        <%= f.input :name, label: 'Nom', required: false, input_html: { class: 'input-row' }  %>
        <%= f.input :email, label: 'Email', required: false, input_html: { class: 'input-row' }  %>
        <%= f.input :phone, label: 'Téléphone', required: false, input_html: { class: 'input-row' }  %>
        <%= f.input :subject, label: 'Sujet', required: false, input_html: { class: 'input-row' }  %>
        <%= f.input :body, label: 'Message', as: :text, required: false, input_html: { id: 'autoresize', contenteditable: true, class: 'input-row' } %>
        <%= button_tag type: 'submit', class: 'btn-submit' do %>
          Envoyer <i class="fas fa-arrow-right"></i>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_banner.html.erb
<div class="banner">
  <div class="banner-content">
    <p id="brand">INTECH</p>
    <h1 id="title"><strong id="hey"> Hey !</strong> Moi c'est Ines Naamane</h1>
    <p id="description"> Développeuse web passionnée, je vous accompagne dans la création de votre identité visuelle.</p>
    <p data-controller="typing-effect" data-typing-effect-words-value='["sites internet", "applications web"]' class="typing-effect">
    Je crée des <span data-typing-effect-target="word"></span><span data-typing-effect-target="cursor" class="typing-effect">|</span>
    </p>
    <p id="brand1">CREATIONS WEB</p>
  </div>

  <div class="banner-content">
   <%= image_tag "bannerpic1.png" %>
  </div>

  <div class="banner-icon">
    <p><i class="fa-solid fa-angles-down"></i></p>
  </div>

</div>

app/views/shared/_footer.html.erb
<footer class="footer-section">
  <div class="section">
    <div class="container">
      <div class="item-social">
        <div class="item">
          <a href="#"><i class="fa-brands fa-facebook"></i></a>
        </div>
        <div class="item">
          <a href="#"><i class="fa-brands fa-twitter"></i></a>
        </div>
        <div class="item">
          <a href="#"><i class="fa-brands fa-linkedin-in"></i></a>
        </div>
      </div>
    </div>
  </div>
  <div class="copyright">
    <p>Copyright &copy; 2023 Ines Naamane. All right reserved. </p>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar">
  <div class="navbar-logo">
    <a class="navbar-brand" href="#">IN</a>
  </div>
  <ul class="navbar-menu">
    <li><a href="#">ACCUEIL</a></li>
    <li><a href="#">SERVICES</a></li>
    <li><a href="#">COMPETENCES</a></li>
    <li><a href="#">PORTFOLIO</a></li>
    <li><a href="#">TEMOIGNAGES</a></li>
    <li><a href="#">CONTACT</a></li>
  </ul>
</nav>